### ISSUE TITLE
Custom JavaScript can be injected (XSS)

### ISSUE THREAD

**Issue by NoRelect** [Jeddsan/JKS#4]
With the following code, I was able to redirect to google:

``` php
$message = "Just some text";
echo($message);
?><script type="text/javascript">window.location = "http://www.google.ch";</script>
```

**Comment by julianschmuckli** [comment]
Some javascript code must be executed for the Kora Android Application.

**Comment by NoRelect** [comment]
True, but i wouldn't allow a redirect by a custom module

**Comment by julianschmuckli** [comment]
Fixed bug in the newest release

**Comment by NoRelect** [comment]
Still possible with the following code:

``` php
?><scrip<script>a</script>t>alert("Hacked")</script><?php
```

Edit: To resolve this issue, loop until there isn't a occurance found

**Comment by NoRelect** [comment]
See issue #6 where the same mistake is used again
